---
driver:
  name: vagrant
  network:
    - ["public_network", bridge: "en0: Wi-Fi (AirPort)"]

provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbose: false
  ansible_verbosity: 5
  playbook: ./playbook.yml

platforms:
#  - name: ubuntu18.04
#    driver_config:
#      box: ubuntu/bionic64
  - name: ubuntu16.04
    driver_config:
      box: bento/ubuntu-16.04

verifier:
  name: inspec
  sudo: true

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
