Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "ubuntu/bionic64"
  c.vm.hostname = "default-ubuntu1804.vagrantup.com"
  c.vm.network(:public_network, {:bridge=>"en0: Wi-Fi (AirPort)"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-ansible_kitchen_ci_example-default-ubuntu1804"
  end
end
